#!/bin/bash

args=("$@")
system=(
  --level=5
  --risk=3
  --random-agent
  --output-dir=/home/yaniv/Downloads/mission/
  --dump-format=html
  --exclude-sysdbs
  --roles
  --priv-esc
  --hostname 
  --current-db

 )
if [[ "$@" == *"-reg"* ]]; then
  extra_args=()
  for arg in "${args[@]}"; do
    [[ "$arg" == "-reg" ]] || extra_args+=("$arg")
  done

  base=( 
    --batch
    --users
    --passwords
    --dump  
    --threads=10 
  )

  echo "Running command: sqlmap ${system[@]} ${base[@]} ${extra_args[@]}"
  sqlmap "${base[@]}" "${extra_args[@]}"

else
  echo "Running command: sqlmap ${system[@]} ${args[@]}"
  sqlmap "${system[@]}" "${args[@]}"
fi
